FROM golang:alpine@sha256:2b74246a3464da3bd3edc19b4c029447c795e772f2068e40f39817ba89ae1054 AS builder
WORKDIR /build
COPY . .
ENV CGO_ENABLED=0
RUN go build -trimpath -ldflags '-s -w' -o /bin/app cmd/ingress/*.go
RUN apk add -U --no-cache ca-certificates

FROM scratch
EXPOSE 8080
COPY --from=builder /bin/app /app
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
ENTRYPOINT ["/app"]
