FROM golang:alpine@sha256:04ec5618ca64098b8325e064aa1de2d3efbbd022a3ac5554d49d5ece99d41ad5 AS builder
WORKDIR /build
COPY . .
ENV CGO_ENABLED=0
RUN go build -trimpath -ldflags '-s -w' -o /bin/app cmd/database/*.go
RUN apk add -U --no-cache ca-certificates

FROM scratch
EXPOSE 50051
COPY --from=builder /bin/app /app
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
ENTRYPOINT ["/app"]
