FROM golang:alpine@sha256:ac09a5f469f307e5da71e766b0bd59c9c49ea460a528cc3e6686513d64a6f1fb AS builder
WORKDIR /build
COPY . .
ENV CGO_ENABLED=0
RUN go build -trimpath -ldflags '-s -w' -o /bin/app cmd/database/*.go
RUN apk add -U --no-cache ca-certificates

FROM scratch
EXPOSE 50051
COPY --from=builder /bin/app /app
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
ENTRYPOINT ["/app"]
