FROM golang:alpine@sha256:0178a641fbb4858c5f1b48e34bdaabe0350a330a1b1149aabd498d0699ff5fb2 AS builder
WORKDIR /build
COPY . .
ENV CGO_ENABLED=0
RUN go build -trimpath -ldflags '-s -w' -o /bin/app cmd/ingress/*.go
RUN apk add -U --no-cache ca-certificates

FROM scratch
EXPOSE 8080
COPY --from=builder /bin/app /app
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
ENTRYPOINT ["/app"]
