FROM golang:alpine@sha256:b6ed3fd0452c0e9bcdef5597f29cc1418f61672e9d3a2f55bf02e7222c014abd AS builder
WORKDIR /build
COPY . .
ENV CGO_ENABLED=0
RUN go build -trimpath -ldflags '-s -w' -o /bin/app cmd/database/*.go
RUN apk add -U --no-cache ca-certificates

FROM scratch
EXPOSE 50051
COPY --from=builder /bin/app /app
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
ENTRYPOINT ["/app"]
